CXX=g++
CXXFLAGS=-I ../SUM -Wall
test: UnitTestSIP UnitTestSenseCycle UnitTestHB
	./UnitTestSIP
	./UnitTestSenseCycle
	./UnitTestHB


clean:
	rm ./UnitTestSIP
	rm ./UnitTestSenseCycle
	rm ./UnitTestHB


